import { apiSlice, ApiResponse } from '@/lib/api';
import { setUserInfo } from '@/shared/store/authSlice';
import { UserData } from '@/shared/store/authSlice';


interface Store {
  id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  description: string;
  address: string;
  status: string;
}


export const profileApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Query endpoint to pull profile data
    getProfileMe: builder.query<ApiResponse<UserData>, void>({
      query: () => ({
        url: '/profile/me/',
        method: 'GET',
      }),
      providesTags: ['User'],
      
      // 3. The Magic Hook: Automatically syncs the successful API response directly into Redux
      async onQueryStarted(_arg, { dispatch, queryFulfilled }) {
        try {
          const { data: responseBody } = await queryFulfilled;
          
          // Double-check your backend response structure. 
          // If the payload wraps the data object inside a '.data' or '.user' parameter:
          const userData = responseBody.data; 

          if (userData) {
            // Automatically push it into your authSlice store layout!
            dispatch(setUserInfo(userData));
          }
        } catch (error) {
          console.error('Failed to automatically sync profile data to auth state:', error);
          // If the profile fetch fails with a 401, your baseQueryWithReauth mutex handles it!
        }
      },
    }),
  }),
});

// Export the hook generated by RTK Query for your client components
export const { useGetProfileMeQuery, useLazyGetProfileMeQuery } = profileApiSlice;