import { Artisan, ArtisanServiceEnum } from '@/shared/service/artisan services/types';

export interface ArtisanWithVisuals extends Artisan {
  businessName: string;
  slug: string;
  aspectRatio: string;
  image: string;
}

export interface ArtisanCategory {
  id: string;
  label: string;
  value: ArtisanServiceEnum | 'ALL';
  count: number;
}

export const CATEGORIES: ArtisanCategory[] = [
  { id: 'cat-all', label: 'All Services', value: 'ALL', count: 12 },
  { id: 'cat-plumber', label: 'Plumbers', value: ArtisanServiceEnum.PLUMBER, count: 3 },
  { id: 'cat-electrician', label: 'Electricians', value: ArtisanServiceEnum.ELECTRICIAN, count: 3 },
  { id: 'cat-painter', label: 'Painters', value: ArtisanServiceEnum.PAINTER, count: 3 },
  { id: 'cat-carpenter', label: 'Carpenters', value: ArtisanServiceEnum.CARPENTER, count: 3 },
];

export const INITIAL_ARTISANS: ArtisanWithVisuals[] = [
  {
    id: 'art-1',
    name: 'Emeka Nwosu',
    businessName: 'BrightFlow Plumbing Services',
    slug: 'brightflow-plumbing-services',
    service: ArtisanServiceEnum.PLUMBER,
    rating: 4.8,
    reviewCount: 124,
    location: 'Lekki, Lagos',
    jobsCompleted: 156,
    skills: ['Pipe Installation', 'Leak Repair', 'Water Heater', 'Bathroom Fitting'],
    hourlyRate: 5000,
    isVerified: true,
    aspectRatio: 'aspect-[3/4]',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800',
  },
  {
    id: 'art-2',
    name: 'Ibrahim Suleiman',
    businessName: 'Suleiman Electrical Solutions',
    slug: 'suleiman-electrical-solutions',
    service: ArtisanServiceEnum.ELECTRICIAN,
    rating: 4.9,
    reviewCount: 98,
    location: 'Ikeja, Lagos',
    jobsCompleted: 203,
    skills: ['Wiring', 'Solar Installation', 'Generator Repair', 'Industrial Power'],
    hourlyRate: 6000,
    isVerified: true,
    aspectRatio: 'aspect-[4/5]',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800',
  },
  {
    id: 'art-3',
    name: 'Blessing Adekunle',
    businessName: 'Perfect Finish Painting',
    slug: 'perfect-finish-painting',
    service: ArtisanServiceEnum.PAINTER,
    rating: 4.7,
    reviewCount: 76,
    location: 'Yaba, Lagos',
    jobsCompleted: 89,
    skills: ['Interior Painting', 'Exterior Painting', 'Wallpaper', '3D Wall Panel'],
    hourlyRate: 4500,
    isVerified: true,
    aspectRatio: 'aspect-[3/2]',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800',
  },
  {
    id: 'art-4',
    name: 'Tunde Ogunleye',
    businessName: 'WoodCraft Works Nigeria',
    slug: 'woodcraft-works-nigeria',
    service: ArtisanServiceEnum.CARPENTER,
    rating: 4.6,
    reviewCount: 112,
    location: 'Surulere, Lagos',
    jobsCompleted: 142,
    skills: ['Furniture Design', 'Roof Repair', 'Cabinet Installation', 'Wood Polishing'],
    hourlyRate: 5500,
    isVerified: true,
    aspectRatio: 'aspect-[4/3]',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=800',
  },
  {
    id: 'art-5',
    name: 'Chinedu Okonkwo',
    businessName: 'Apex Pipeworks & Drainage',
    slug: 'apex-pipeworks-drainage',
    service: ArtisanServiceEnum.PLUMBER,
    rating: 4.9,
    reviewCount: 142,
    location: 'Victoria Island, Lagos',
    jobsCompleted: 180,
    skills: ['Borehole Pumps', 'Drainage Clearing', 'PEX Piping', 'Water Filters'],
    hourlyRate: 7000,
    isVerified: true,
    aspectRatio: 'aspect-[3/4]',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800',
  },
  {
    id: 'art-6',
    name: 'Amina Bello',
    businessName: 'VoltTech Power & Solar',
    slug: 'volttech-power-solar',
    service: ArtisanServiceEnum.ELECTRICIAN,
    rating: 4.8,
    reviewCount: 88,
    location: 'Garki, Abuja',
    jobsCompleted: 110,
    skills: ['Inverter Setup', 'Smart Switches', 'Fault Detection', 'Distribution Boards'],
    hourlyRate: 6500,
    isVerified: true,
    aspectRatio: 'aspect-[4/5]',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800',
  },
  {
    id: 'art-7',
    name: 'Samuel Danjuma',
    businessName: 'Prime Color Coatings',
    slug: 'prime-color-coatings',
    service: ArtisanServiceEnum.PAINTER,
    rating: 4.5,
    reviewCount: 64,
    location: 'Maitama, Abuja',
    jobsCompleted: 75,
    skills: ['Epoxy Flooring', 'Screeding', 'Textured Paint', 'POP Finishing'],
    hourlyRate: 5000,
    isVerified: false,
    aspectRatio: 'aspect-[3/2]',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800',
  },
  {
    id: 'art-8',
    name: 'Kemi Adeleke',
    businessName: 'Kemi Studio Carpentry & Interior',
    slug: 'kemi-studio-carpentry-interior',
    service: ArtisanServiceEnum.CARPENTER,
    rating: 4.9,
    reviewCount: 130,
    location: 'Ajah, Lagos',
    jobsCompleted: 165,
    skills: ['Modular Kitchens', 'Custom Wardrobes', 'Door Fitting', 'TV Console Units'],
    hourlyRate: 6000,
    isVerified: true,
    aspectRatio: 'aspect-[4/3]',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800',
  },
  {
    id: 'art-9',
    name: 'Usman Garba',
    businessName: 'Kano Master Plumbers',
    slug: 'kano-master-plumbers',
    service: ArtisanServiceEnum.PLUMBER,
    rating: 4.6,
    reviewCount: 52,
    location: 'Nasarawa, Kano',
    jobsCompleted: 68,
    skills: ['Septic Tank Maintenance', 'Pipe Laying', 'Overhead Tank Install', 'Faucets'],
    hourlyRate: 4000,
    isVerified: true,
    aspectRatio: 'aspect-[3/4]',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800',
  },
  {
    id: 'art-10',
    name: 'Folake Alabi',
    businessName: 'BrightSpark Electricals',
    slug: 'brightspark-electricals',
    service: ArtisanServiceEnum.ELECTRICIAN,
    rating: 4.7,
    reviewCount: 115,
    location: 'Bodija, Ibadan',
    jobsCompleted: 130,
    skills: ['CCTV Wiring', 'Changeover Switches', 'Light Fixtures', 'Breaker Replacement'],
    hourlyRate: 4500,
    isVerified: false,
    aspectRatio: 'aspect-[4/5]',
    image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?q=80&w=800',
  },
  {
    id: 'art-11',
    name: 'Victor Nwachukwu',
    businessName: 'Vanguard Wall Art & Paint',
    slug: 'vanguard-wall-art-paint',
    service: ArtisanServiceEnum.PAINTER,
    rating: 4.8,
    reviewCount: 91,
    location: 'Port Harcourt, Rivers',
    jobsCompleted: 104,
    skills: ['Exterior Weatherproofing', 'Graffiti & Mural Art', 'Stucco Painting', 'Sanding'],
    hourlyRate: 5500,
    isVerified: true,
    aspectRatio: 'aspect-[3/2]',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=800',
  },
  {
    id: 'art-12',
    name: 'Tochukwu Eze',
    businessName: 'Eze & Sons Joinery',
    slug: 'eze-sons-joinery',
    service: ArtisanServiceEnum.CARPENTER,
    rating: 4.7,
    reviewCount: 84,
    location: 'Enugu Urban, Enugu',
    jobsCompleted: 95,
    skills: ['Hardwood Flooring', 'Bed Frames', 'Office Desks', 'Timber Framing'],
    hourlyRate: 4800,
    isVerified: true,
    aspectRatio: 'aspect-[4/3]',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800',
  },
];