import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 36,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#1e293b',
  },
  headerBanner: {
    backgroundColor: '#1b5e32',
    borderRadius: 12,
    padding: 20,
    color: '#FFFFFF',
    marginBottom: 20,
  },
  brandTitle: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: '#80da90',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  docTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  amountLabel: {
    fontSize: 8,
    textTransform: 'uppercase',
    color: '#9bf7aa',
    marginBottom: 2,
  },
  amountValue: {
    fontSize: 26,
    fontWeight: 'bold',
  },
  sectionCard: {
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    padding: 16,
    marginBottom: 20,
  },
  statusBadge: {
    backgroundColor: '#e8f5e9',
    padding: '6 12',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusText: {
    color: '#2a8545',
    fontSize: 11,
    fontWeight: 'bold',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  label: {
    color: '#5f5e5e',
  },
  value: {
    fontWeight: 'bold',
    color: '#0f172a',
  },
  footer: {
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 12,
    textAlign: 'center',
    color: '#5f5e5e',
    fontSize: 8,
  },
});

export interface ReceiptData {
  reference: string;
  title: string;
  category: string;
  date: string;
  amount: number;
  provider: string;
  property: string;
}

export function ReceiptPDF({ data }: { data: ReceiptData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBanner}>
          <Text style={styles.brandTitle}>Conekta Finance</Text>
          <Text style={styles.docTitle}>Official Transaction Receipt</Text>
          <Text style={styles.amountLabel}>Total Amount Paid</Text>
          <Text style={styles.amountValue}>
            NGN {data.amount.toLocaleString('en-NG')}
          </Text>
        </View>

        <View style={styles.sectionCard}>
          <View style={styles.statusBadge}>
            <Text style={styles.statusText}>Status: Payment Completed</Text>
            <Text style={{ fontSize: 9, color: '#5f5e5e' }}>{data.date}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Description</Text>
            <Text style={styles.value}>{data.title}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Category</Text>
            <Text style={styles.value}>{data.category}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Service Provider</Text>
            <Text style={styles.value}>{data.provider}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Property Location</Text>
            <Text style={styles.value}>{data.property}</Text>
          </View>

          <View style={[styles.row, { borderBottomWidth: 0 }]}>
            <Text style={styles.label}>Transaction Reference</Text>
            <Text style={[styles.value, { fontFamily: 'Courier' }]}>{data.reference}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>This is an automated official receipt generated by Conekta housing platform.</Text>
          <Text style={{ marginTop: 2 }}>Reference Code: {data.reference}</Text>
        </View>
      </Page>
    </Document>
  );
}